In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/aist4010-spring2022-a0/sample_submission.csv
/kaggle/input/aist4010-spring2022-a0/X_test.csv
/kaggle/input/aist4010-spring2022-a0/y_train.csv
/kaggle/input/aist4010-spring2022-a0/X_train.csv
/kaggle/input/aist4010-spring2022-a0/iris_information.txt


In [2]:
X_train = np.loadtxt(open("/kaggle/input/aist4010-spring2022-a0/X_train.csv","rb"), delimiter=",", skiprows=0)
y_train = np.loadtxt(open("/kaggle/input/aist4010-spring2022-a0/y_train.csv","rb"), delimiter=",", skiprows=0)

In [3]:
print('X_train:\n', X_train[0:3])
print('y_train:\n', y_train[0:3])

X_train:
 [[7.7 2.6 6.9 2.3]
 [5.7 3.8 1.7 0.3]
 [5.  3.6 1.4 0.2]]
y_train:
 [2. 0. 0.]


In [4]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X_train, y_train)

GaussianNB()

In [5]:
X_test = np.loadtxt(open("/kaggle/input/aist4010-spring2022-a0/X_test.csv","rb"), delimiter=",", skiprows=0)
y_pred = clf.predict(X_test)

In [6]:
import pandas as pd
output = {'Predicted':y_pred}
output_df = pd.DataFrame(output)

In [7]:
output_df.head(3)

Predicted
0        0.0
1        1.0
2        1.0

In [8]:
output_df.to_csv('output.csv', index_label='Id')